export const API_URL = 'http://localhost:3000';
export const LOAD_PROFILE_DATA = 'LOAD_PROFILE_DATA';
export const LOAD_PROFILE_DATA_SUCCESS = 'LOAD_PROFILE_DATA_SUCCESS';
export const LOAD_PROFILE_DATA_FAILED = 'LOAD_PROFILE_DATA_FAILED';
